### ISSUE TITLE
Tracking issue: Stylo `v0.2.0` release

### ISSUE THREAD

**Issue by nicoburns** [servo/stylo#95]
Tracks the initial `0.2` release of Stylo on crates.io.

## Crate status

| Crate              | Changed | Notes                                                           | Owner(s)           | Team |
| ---                | ---     | ---                                                             | ---                | --   |
| to_shmem           | No      | Published as `stylo_to_shmem` and  `to_shmem`.                  | delan              | Yes  |
| to_shmem_derive    | No      | Published as `stylo_to_shmem_derive` and `to_shmem_derive`      | delan              | Yes  |
| malloc_size_of     | ?       | To be published as `stylo_malloc_size_of`                                                             | nicoburns          | No   |
| servo_arc          | No      | Published as both servo_arc and stylo_arc. Both are up to date. | emilio, simonsapin | Yes  |
| selectors          | Yes     | Small but breaking change                                       | emilio, simonsapin | Yes  |
| stylo_atoms        | Yes     | Atoms list changed                                              | nicoburns          | No   |
| stylo_dom          | Yes     | Now depends on malloc_style_of                                  | nicoburns          | No   |
| stylo_static_prefs | Yes     | New prefs added                                                 | nicoburns          | No   |
| stylo_config       | Yes     | Non-breaking change                                             | nicoburns          | No   |
| style_derive       | Yes     | Non-breaking change                                             | nicoburns          | No   |
| style_traits       | Yes     | To be published as stylo_traits                                 | nicoburns          | No   |
| style              | Yes     | To be published as stylo                                        | nicoburns          | No   |

## Depends on
- [x] https://github.com/servo/stylo/pull/92
- [x] https://github.com/servo/stylo/pull/91
- [ ] Don't use a cross-crate `include!()` macro for counter style atoms (https://github.com/servo/stylo/pull/99)
- [ ] Rename crates from `style` to `stylo` (https://bugzilla.mozilla.org/show_bug.cgi?id=1938783)
    - [ ] Crates that are upstream (`style`, `style_traits` and `style_derive`, `malloc_size_of`)
    - [x] Crates that are not upstream (`atoms`, `dom`, `style_config`, `style_static_prefs`)
- [ ] Add `README.md` to `stylo` crate (this is what will appear on the `crates.io` listing).
- [ ] Update `Cargo.toml` metadata for release. Ensure that all crates have up-to-date listings for the following keys (`version`, `authors`, `documentation`, `description`, `repository`, `license`, `edition`, `publish`)
- [ ] Bump version numbers for release

### Optional tasks
- [x] Upgrade crates to 2021 edition
- [ ] Upstream remaining diff
- [ ] Re-export crates from `style` crate to make it easier to depend on
- [ ] Improve `lib.rs` documentation for `stylo` crate
- [ ] Publish `malloc_size_of` on crates.io ([bugzilla.mozilla.org#1933341](https://bugzilla.mozilla.org/show_bug.cgi?id=1933341))
