### ISSUE TITLE
Tracking issue: eliminate diff with upstream

### ISSUE THREAD

**Issue by nicoburns** [servo/stylo#96]
We want to upstream as many changes as possible.

### Current commits containing diffs on top of upstream

- [ ] [Commit our changes on top of upstream Stylo](https://github.com/servo/stylo/commit/b1317ca7bf37e94b1c5d30809c55bf4fc41e9a13)
- [ ] [Fixup for](https://github.com/servo/stylo/commit/6605bdbb042735492efaa7530c40378cc1c21afa) https://phabricator.services.mozilla.com/D226265
- [ ] [Enable `prefers-color-scheme`](https://github.com/servo/stylo/commit/16c1b6858581ab837f04a30cc5bc762ca1cbad23)
- [x] [Remove Servo-specific code from `malloc_size_of`](https://github.com/servo/stylo/commit/639802f35677f444a66fa1cf01bb579065cb2a27)
- [x] [Remove dependency on webrender_api](https://github.com/servo/stylo/commit/4eb9da3b639baab6b16a43b8512b5c11c087fc2c)

(ticked commits have been upstreamed since the more recent sync)

###  Upstreamed code

- [x] https://github.com/servo/stylo/pull/92
- [x] https://github.com/servo/stylo/pull/91
- [x] https://github.com/servo/stylo/pull/87
- [x] https://github.com/servo/stylo/pull/80

**Comment by Loirooriol** [comment]
> [Fixup for](https://github.com/servo/stylo/commit/6605bdbb042735492efaa7530c40378cc1c21afa) https://phabricator.services.mozilla.com/D226265

This one was aligning downstream with upstream.
